-- ============================================================
-- TTZ FITNESS CLUB — Production-Ready Supabase Migration v2.0
-- ============================================================
-- DESIGN PRINCIPLES:
--   • Supabase Auth manages all credentials (no password columns)
--   • Computed fields (days_remaining, status) live in VIEWs only
--   • 3NF: member_name is never stored redundantly; derived via JOIN
--   • Idempotent: safe to run multiple times (IF NOT EXISTS, ON CONFLICT)
--   • Soft deletes on mutable entities (deleted_at)
--   • Full audit trail (created_at, updated_at, created_by, updated_by)
--   • RLS: development-safe policies with production upgrade path
--
-- EXECUTION: Paste the entire file into Supabase SQL Editor and click Run.
-- The final SELECT at the bottom verifies all tables were created.
-- ============================================================


-- ============================================================
-- SECTION 0: HELPER FUNCTIONS
-- ============================================================

-- Automatically updates `updated_at` to NOW() on any row update.
CREATE OR REPLACE FUNCTION public.handle_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$;

COMMENT ON FUNCTION public.handle_updated_at IS
  'Generic trigger function that sets updated_at = NOW() before any UPDATE.';


-- ============================================================
-- SECTION 1: PROFILES
-- Extends auth.users with gym-specific staff/admin data.
-- Passwords are NEVER stored here — Supabase Auth manages them.
-- ============================================================
CREATE TABLE IF NOT EXISTS public.profiles (
  -- Links 1:1 to auth.users. Cascade delete removes profile when auth user is deleted.
  id             UUID       PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  display_name   TEXT       NOT NULL,
  role           TEXT       NOT NULL DEFAULT 'staff'
                              CHECK (role IN ('super_admin', 'admin', 'manager', 'staff', 'trainer')),
  avatar_url     TEXT,
  phone          TEXT,
  is_active      BOOLEAN    NOT NULL DEFAULT TRUE,
  -- Audit
  created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at     TIMESTAMPTZ NOT NULL DEFAULT NOW()
  -- NOTE: No deleted_at here. Disable users via Supabase Auth dashboard instead.
);

COMMENT ON TABLE public.profiles IS
  'Gym staff and admin profiles. Linked 1:1 to auth.users via UUID.
   Role controls UI access. Passwords are managed by Supabase Auth.
   PRODUCTION: Add gym_id for multi-tenant isolation.';

COMMENT ON COLUMN public.profiles.role IS
  'super_admin: full access | admin: manage members/payments |
   manager: reports + renewals | staff: attendance + check-in | trainer: own clients only';

CREATE INDEX IF NOT EXISTS idx_profiles_role     ON public.profiles(role);
CREATE INDEX IF NOT EXISTS idx_profiles_active   ON public.profiles(is_active) WHERE is_active = TRUE;

DROP TRIGGER IF EXISTS trg_profiles_updated_at ON public.profiles;
CREATE TRIGGER trg_profiles_updated_at
  BEFORE UPDATE ON public.profiles
  FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();

-- Auto-create a profile row whenever a new Supabase Auth user is registered.
CREATE OR REPLACE FUNCTION public.handle_new_auth_user()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER SET search_path = ''
AS $$
BEGIN
  INSERT INTO public.profiles (id, display_name, role)
  VALUES (
    NEW.id,
    COALESCE(
      NEW.raw_user_meta_data ->> 'display_name',
      split_part(NEW.email, '@', 1)
    ),
    COALESCE(NEW.raw_user_meta_data ->> 'role', 'staff')
  )
  ON CONFLICT (id) DO NOTHING;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_on_auth_user_created ON auth.users;
CREATE TRIGGER trg_on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_auth_user();


-- ============================================================
-- SECTION 2: MEMBERSHIP PLANS  (Lookup / Reference table)
-- Normalized plan catalog. Members reference plan_id.
-- ============================================================
CREATE TABLE IF NOT EXISTS public.membership_plans (
  id             BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name           TEXT        NOT NULL UNIQUE,
  duration_days  INTEGER     NOT NULL CHECK (duration_days > 0),
  price          NUMERIC(10, 2) NOT NULL CHECK (price >= 0),
  is_active      BOOLEAN     NOT NULL DEFAULT TRUE,
  -- Audit
  created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by     UUID        REFERENCES public.profiles(id) ON DELETE SET NULL,
  updated_by     UUID        REFERENCES public.profiles(id) ON DELETE SET NULL
);

COMMENT ON TABLE public.membership_plans IS
  'Catalog of membership plans available at the gym.
   Members.plan_id is a FK here; members.plan (TEXT) is kept as a denormalized display copy.';

DROP TRIGGER IF EXISTS trg_membership_plans_updated_at ON public.membership_plans;
CREATE TRIGGER trg_membership_plans_updated_at
  BEFORE UPDATE ON public.membership_plans
  FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();

-- Seed default plans — idempotent via ON CONFLICT
INSERT INTO public.membership_plans (name, duration_days, price) VALUES
  ('Monthly',   30,  2500.00),
  ('Quarterly', 90,  6500.00),
  ('Annual',    365, 22000.00),
  ('Drop-in',   1,   200.00)
ON CONFLICT (name) DO NOTHING;


-- ============================================================
-- SECTION 3: TRAINERS
-- Trainer profiles (distinct from staff profiles).
-- ============================================================
CREATE TABLE IF NOT EXISTS public.trainers (
  id                BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name              TEXT        NOT NULL,
  specialty         TEXT        NOT NULL,
  phone             TEXT,
  email             TEXT        UNIQUE,
  experience        TEXT,
  availability      TEXT,
  rating            NUMERIC(3, 1) NOT NULL DEFAULT 5.0
                      CHECK (rating >= 0.0 AND rating <= 5.0),
  is_active         BOOLEAN     NOT NULL DEFAULT TRUE,
  -- Soft delete: retain records for audit / historical payments
  deleted_at        TIMESTAMPTZ,
  -- Audit
  created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by        UUID        REFERENCES public.profiles(id) ON DELETE SET NULL,
  updated_by        UUID        REFERENCES public.profiles(id) ON DELETE SET NULL
);

COMMENT ON TABLE public.trainers IS
  'Trainer profiles. Soft-deleted via deleted_at so member relationships are preserved.
   assignedMembers count is derived at query time (COUNT of members.trainer_id), never stored.';

CREATE INDEX IF NOT EXISTS idx_trainers_active    ON public.trainers(is_active) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_trainers_email     ON public.trainers(email);

DROP TRIGGER IF EXISTS trg_trainers_updated_at ON public.trainers;
CREATE TRIGGER trg_trainers_updated_at
  BEFORE UPDATE ON public.trainers
  FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();


-- ============================================================
-- SECTION 4: MEMBERS  (Core operational table)
-- `days_remaining` and `status` are NOT columns here.
-- They are computed in members_view using expiry_date vs CURRENT_DATE.
-- ============================================================
CREATE TABLE IF NOT EXISTS public.members (
  id              BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name            TEXT        NOT NULL,
  phone           TEXT        NOT NULL,
  email           TEXT,
  -- Plan: FK to catalog + denormalized text copy for UI display
  plan_id         BIGINT      REFERENCES public.membership_plans(id) ON DELETE RESTRICT,
  plan            TEXT        NOT NULL,
  join_date       DATE        NOT NULL DEFAULT CURRENT_DATE,
  expiry_date     DATE        NOT NULL,
  -- Staff / trainer assignment
  trainer_id      BIGINT      REFERENCES public.trainers(id) ON DELETE SET NULL,
  -- Body composition (optional)
  weight          NUMERIC(5, 2),
  target_weight   NUMERIC(5, 2),
  height          NUMERIC(5, 2),
  body_fat        NUMERIC(5, 2),
  -- Progress media
  before_image    TEXT,
  after_image     TEXT,
  -- Misc
  last_visit      DATE,
  notes           TEXT,
  -- Soft delete: never hard-delete members; preserves payment/attendance history
  deleted_at      TIMESTAMPTZ,
  -- Audit
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by      UUID        REFERENCES public.profiles(id) ON DELETE SET NULL,
  updated_by      UUID        REFERENCES public.profiles(id) ON DELETE SET NULL,
  -- Constraints
  CONSTRAINT chk_members_expiry_after_join CHECK (expiry_date >= join_date),
  CONSTRAINT chk_members_phone_length CHECK (LENGTH(TRIM(phone)) >= 7)
);

COMMENT ON TABLE public.members IS
  'Gym member roster. Use members_view for all SELECT queries — it computes
   days_remaining and status dynamically from expiry_date.
   Phone uniqueness is enforced only on non-deleted rows (partial index below).
   NEVER store member_name in payments/attendance — JOIN on member_id instead.';

COMMENT ON COLUMN public.members.plan IS
  'Denormalized plan name for fast display. Keep in sync with membership_plans.name.
   plan_id is the authoritative FK reference.';

-- Unique phone among active (non-deleted) members only
CREATE UNIQUE INDEX IF NOT EXISTS idx_members_phone_unique_active
  ON public.members(phone) WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_members_expiry      ON public.members(expiry_date)  WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_members_trainer_id  ON public.members(trainer_id)   WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_members_plan_id     ON public.members(plan_id);
CREATE INDEX IF NOT EXISTS idx_members_email       ON public.members(email)         WHERE deleted_at IS NULL AND email IS NOT NULL;

DROP TRIGGER IF EXISTS trg_members_updated_at ON public.members;
CREATE TRIGGER trg_members_updated_at
  BEFORE UPDATE ON public.members
  FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();


-- ──────────────────────────────────────────────────────────────
-- VIEW: members_view  — use this for ALL SELECT queries in the app
-- ──────────────────────────────────────────────────────────────
CREATE OR REPLACE VIEW public.members_view AS
SELECT
  m.id,
  m.name,
  m.phone,
  m.email,
  m.plan,
  m.plan_id,
  m.join_date,
  m.expiry_date,
  -- days_remaining: computed live from today's date, minimum 0
  GREATEST(0, (m.expiry_date - CURRENT_DATE)::INTEGER)        AS days_remaining,
  -- status: derived from expiry_date vs CURRENT_DATE
  CASE
    WHEN m.expiry_date < CURRENT_DATE               THEN 'expired'
    WHEN m.expiry_date <= (CURRENT_DATE + 5)        THEN 'expiring'
    ELSE                                                 'active'
  END                                                          AS status,
  m.trainer_id,
  m.weight,
  m.target_weight,
  m.height,
  m.body_fat,
  m.before_image,
  m.after_image,
  m.last_visit,
  m.notes,
  m.created_at,
  m.updated_at,
  m.created_by,
  m.updated_by
FROM public.members m
WHERE m.deleted_at IS NULL;

COMMENT ON VIEW public.members_view IS
  'Active-only members with computed days_remaining and status.
   All application SELECT queries MUST use this view, not the base table.
   INSERT / UPDATE / DELETE still target the base members table.';


-- ============================================================
-- SECTION 5: PAYMENTS  (3NF — member_name NOT stored)
-- ============================================================
CREATE TABLE IF NOT EXISTS public.payments (
  id          BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  -- FK only — member_name comes from JOIN with members_view
  member_id   BIGINT      NOT NULL REFERENCES public.members(id) ON DELETE RESTRICT,
  amount      NUMERIC(10, 2) NOT NULL CHECK (amount > 0),
  plan        TEXT        NOT NULL,
  date        DATE        NOT NULL DEFAULT CURRENT_DATE,
  method      TEXT        NOT NULL DEFAULT 'Cash'
                CHECK (method IN ('Cash', 'UPI', 'Card', 'Bank Transfer', 'Other')),
  status      TEXT        NOT NULL DEFAULT 'paid'
                CHECK (status IN ('paid', 'pending', 'refunded', 'failed')),
  notes       TEXT,
  -- Soft delete: keep audit trail even after correction
  deleted_at  TIMESTAMPTZ,
  -- Audit
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by  UUID        REFERENCES public.profiles(id) ON DELETE SET NULL,
  updated_by  UUID        REFERENCES public.profiles(id) ON DELETE SET NULL
);

COMMENT ON TABLE public.payments IS
  '3NF: member_name is NOT stored. Always JOIN with members_view to get name.
   Use payments_view for display-layer queries.
   Soft-deleted via deleted_at; refunded/failed payments are status-updated, not deleted.';

CREATE INDEX IF NOT EXISTS idx_payments_member_id ON public.payments(member_id);
CREATE INDEX IF NOT EXISTS idx_payments_date      ON public.payments(date)   WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_payments_status    ON public.payments(status) WHERE deleted_at IS NULL;

DROP TRIGGER IF EXISTS trg_payments_updated_at ON public.payments;
CREATE TRIGGER trg_payments_updated_at
  BEFORE UPDATE ON public.payments
  FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();

-- VIEW: payments_view — provides member_name via JOIN for UI display
CREATE OR REPLACE VIEW public.payments_view AS
SELECT
  p.id,
  p.member_id,
  m.name          AS member_name,
  m.phone         AS member_phone,
  p.amount,
  p.plan,
  p.date,
  p.method,
  p.status,
  p.notes,
  p.created_at,
  p.updated_at,
  p.created_by
FROM public.payments p
JOIN public.members m ON m.id = p.member_id
WHERE p.deleted_at IS NULL;

COMMENT ON VIEW public.payments_view IS
  'Payments joined with member name/phone for display.
   member_name is derived via JOIN — never stored redundantly.';


-- ============================================================
-- SECTION 6: ATTENDANCE  (3NF — member_name NOT stored)
-- One row per member per day enforced by UNIQUE constraint.
-- ============================================================
CREATE TABLE IF NOT EXISTS public.attendance (
  id              BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  -- FK only — member_name comes from JOIN with members_view
  member_id       BIGINT      NOT NULL REFERENCES public.members(id) ON DELETE CASCADE,
  date            DATE        NOT NULL DEFAULT CURRENT_DATE,
  check_in_time   TEXT,      -- stored as text e.g. "10:30 AM" for UI compatibility
  check_out_time  TEXT,
  status          TEXT        NOT NULL DEFAULT 'present'
                    CHECK (status IN ('present', 'absent', 'late')),
  notes           TEXT,
  -- Audit
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  -- Enforce: one attendance record per member per calendar day
  CONSTRAINT uq_attendance_member_date UNIQUE (member_id, date)
);

COMMENT ON TABLE public.attendance IS
  '3NF: member_name is NOT stored. Join with members_view to get it.
   UNIQUE(member_id, date) prevents duplicate check-ins on the same day.
   Use attendance_view for all display queries.
   No soft delete: attendance records are factual; corrections go via UPDATE.';

CREATE INDEX IF NOT EXISTS idx_attendance_member_id ON public.attendance(member_id);
CREATE INDEX IF NOT EXISTS idx_attendance_date       ON public.attendance(date);

DROP TRIGGER IF EXISTS trg_attendance_updated_at ON public.attendance;
CREATE TRIGGER trg_attendance_updated_at
  BEFORE UPDATE ON public.attendance
  FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();

-- VIEW: attendance_view — provides member info via JOIN
CREATE OR REPLACE VIEW public.attendance_view AS
SELECT
  a.id,
  a.member_id,
  m.name          AS member_name,
  m.phone         AS member_phone,
  a.date,
  a.check_in_time,
  a.check_out_time,
  a.status,
  a.notes,
  a.created_at,
  a.updated_at
FROM public.attendance a
JOIN public.members m ON m.id = a.member_id
WHERE m.deleted_at IS NULL;

COMMENT ON VIEW public.attendance_view IS
  'Attendance with member name/phone derived via JOIN.
   Excludes attendance for soft-deleted members.';


-- ============================================================
-- SECTION 7: SETTINGS  (Key-value gym configuration)
-- ============================================================
CREATE TABLE IF NOT EXISTS public.settings (
  key         TEXT        PRIMARY KEY,
  value       TEXT,
  description TEXT,
  -- Audit
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_by  UUID        REFERENCES public.profiles(id) ON DELETE SET NULL
);

COMMENT ON TABLE public.settings IS
  'Global gym configuration as key-value pairs.
   Key is the PK (no duplicates). No soft delete needed — use UPDATE.
   PRODUCTION: Move sensitive values (API keys) to Supabase Vault.';

DROP TRIGGER IF EXISTS trg_settings_updated_at ON public.settings;
CREATE TRIGGER trg_settings_updated_at
  BEFORE UPDATE ON public.settings
  FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();

-- Seed default settings — idempotent via ON CONFLICT DO NOTHING
INSERT INTO public.settings (key, value, description) VALUES
  ('gym_name',           'TTZ Fitness Club',           'Display name of the gym'),
  ('tagline',            'Transform. Thrive. Triumph.', 'Branding tagline'),
  ('gym_type',           'Premium Fitness Center',     'Gym type descriptor'),
  ('primary_phone',      '',                           'Primary contact number'),
  ('secondary_phone',    '',                           'Secondary contact number'),
  ('email',              '',                           'Primary contact email'),
  ('instagram',          '',                           'Instagram handle'),
  ('address',            '',                           'Gym physical address'),
  ('opening_time',       '05:00',                      'Daily opening time (HH:MM)'),
  ('closing_time',       '23:00',                      'Daily closing time (HH:MM)'),
  ('expiry_alerts',      'true',                       'Enable membership expiry alerts'),
  ('payment_reminders',  'true',                       'Enable pending payment reminders'),
  ('new_member_alerts',  'true',                       'Enable new member notifications'),
  ('brand_color',        'amber',                      'UI brand color'),
  ('webhook_url',        '',                           'WhatsApp webhook target URL'),
  ('twilio_sid',         '',                           'Twilio Account SID'),
  ('twilio_phone',       '',                           'Twilio sender phone number')
ON CONFLICT (key) DO NOTHING;


-- ============================================================
-- SECTION 8: NOTIFICATIONS  (In-app notification feed)
-- ============================================================
CREATE TABLE IF NOT EXISTS public.notifications (
  id          BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title       TEXT        NOT NULL,
  message     TEXT        NOT NULL,
  category    TEXT        NOT NULL DEFAULT 'system'
                CHECK (category IN ('expiry', 'payment', 'attendance', 'member', 'system')),
  is_read     BOOLEAN     NOT NULL DEFAULT FALSE,
  -- Optional: link to specific member
  member_id   BIGINT      REFERENCES public.members(id) ON DELETE CASCADE,
  -- Audit
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by  UUID        REFERENCES public.profiles(id) ON DELETE SET NULL
);

COMMENT ON TABLE public.notifications IS
  'In-app notification entries. member_id is optional (NULL = gym-wide notification).
   No soft delete — read notifications are simply deleted or ignored.
   Clean up old read notifications periodically.';

CREATE INDEX IF NOT EXISTS idx_notifications_is_read    ON public.notifications(is_read);
CREATE INDEX IF NOT EXISTS idx_notifications_created_at ON public.notifications(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_notifications_member_id  ON public.notifications(member_id);
CREATE INDEX IF NOT EXISTS idx_notifications_category   ON public.notifications(category);


-- ============================================================
-- SECTION 9: ACTIVITIES  (Dashboard activity feed / audit log)
-- Append-only. Never updated or deleted in normal operation.
-- ============================================================
CREATE TABLE IF NOT EXISTS public.activities (
  id          BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type        TEXT        NOT NULL
                CHECK (type IN ('new_member', 'payment', 'renewal', 'attendance', 'trainer', 'system')),
  -- member_id nullable: system events have no member
  member_id   BIGINT      REFERENCES public.members(id) ON DELETE SET NULL,
  -- name: human-readable subject (member name, trainer name, etc.)
  name        TEXT        NOT NULL,
  -- action: human-readable description ("joined the gym", "paid ₹3,000")
  action      TEXT        NOT NULL,
  -- time: relative display text ("Just now", "2 hours ago") — stored for feed display
  time        TEXT        NOT NULL DEFAULT 'Just now',
  -- Audit
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by  UUID        REFERENCES public.profiles(id) ON DELETE SET NULL
);

COMMENT ON TABLE public.activities IS
  'Append-only activity feed for the dashboard.
   Old entries can be archived after 90 days via a scheduled job.
   member_id is nullable (SET NULL on member delete keeps the log entry).';

CREATE INDEX IF NOT EXISTS idx_activities_created_at ON public.activities(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_activities_member_id  ON public.activities(member_id);
CREATE INDEX IF NOT EXISTS idx_activities_type       ON public.activities(type);


-- ============================================================
-- SECTION 10: WHATSAPP CONFIG  (Single-row messaging config)
-- ============================================================
CREATE TABLE IF NOT EXISTS public.whatsapp_config (
  id                    BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  provider              TEXT        NOT NULL DEFAULT 'twilio'
                          CHECK (provider IN ('twilio', 'wati', 'interakt', 'other')),
  -- PRODUCTION: Move api_key to Supabase Vault. Never commit API keys.
  api_key               TEXT,
  phone_number          TEXT,
  is_connected          BOOLEAN     NOT NULL DEFAULT FALSE,
  reminder_enabled      BOOLEAN     NOT NULL DEFAULT TRUE,
  expiry_reminder_days  INTEGER     NOT NULL DEFAULT 7  CHECK (expiry_reminder_days > 0),
  low_attendance_days   INTEGER     NOT NULL DEFAULT 5  CHECK (low_attendance_days > 0),
  custom_message        TEXT        DEFAULT 'Hi {name}, your TTZ Fitness membership expires on {expiry_date}. Renew now to stay active!',
  send_method           TEXT        NOT NULL DEFAULT 'whatsapp'
                          CHECK (send_method IN ('whatsapp', 'sms', 'both')),
  auto_send             BOOLEAN     NOT NULL DEFAULT FALSE,
  -- Audit
  updated_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_by            UUID        REFERENCES public.profiles(id) ON DELETE SET NULL,
  -- Enforces this is always a single-row table
  CONSTRAINT whatsapp_config_single_row CHECK (id = 1)
);

COMMENT ON TABLE public.whatsapp_config IS
  'Single-row messaging integration config (CONSTRAINT id=1 enforces singleton).
   PRODUCTION: api_key MUST be stored in Supabase Vault, not here.
   Use Supabase Edge Functions to send messages server-side.';

DROP TRIGGER IF EXISTS trg_whatsapp_config_updated_at ON public.whatsapp_config;
CREATE TRIGGER trg_whatsapp_config_updated_at
  BEFORE UPDATE ON public.whatsapp_config
  FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();

INSERT INTO public.whatsapp_config (id, provider, send_method, is_connected)
VALUES (1, 'twilio', 'whatsapp', FALSE)
ON CONFLICT DO NOTHING;


-- ============================================================
-- SECTION 11: REMINDER LOGS  (3NF — member_name NOT stored)
-- ============================================================
CREATE TABLE IF NOT EXISTS public.reminder_logs (
  id          BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  -- Nullable: system-generated test messages may have no member
  member_id   BIGINT      REFERENCES public.members(id) ON DELETE SET NULL,
  type        TEXT        NOT NULL
                CHECK (type IN ('expiry', 'payment', 'attendance', 'promo', 'test', 'welcome')),
  message     TEXT        NOT NULL,
  method      TEXT        NOT NULL CHECK (method IN ('whatsapp', 'sms', 'both')),
  status      TEXT        NOT NULL DEFAULT 'pending'
                CHECK (status IN ('pending', 'delivered', 'failed', 'bounced')),
  sent_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  -- Audit
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by  UUID        REFERENCES public.profiles(id) ON DELETE SET NULL
);

COMMENT ON TABLE public.reminder_logs IS
  '3NF: member_name NOT stored. Use reminder_logs_view for display queries.
   Append-only audit log. member_id SET NULL if member is deleted (log is retained).
   No soft delete: logs are immutable records.';

CREATE INDEX IF NOT EXISTS idx_reminder_logs_member_id ON public.reminder_logs(member_id);
CREATE INDEX IF NOT EXISTS idx_reminder_logs_sent_at   ON public.reminder_logs(sent_at DESC);
CREATE INDEX IF NOT EXISTS idx_reminder_logs_type      ON public.reminder_logs(type);
CREATE INDEX IF NOT EXISTS idx_reminder_logs_status    ON public.reminder_logs(status);

-- VIEW: reminder_logs_view
CREATE OR REPLACE VIEW public.reminder_logs_view AS
SELECT
  rl.id,
  rl.member_id,
  m.name          AS member_name,
  m.phone         AS member_phone,
  rl.type,
  rl.message,
  rl.method,
  rl.status,
  rl.sent_at,
  rl.created_at
FROM public.reminder_logs rl
-- LEFT JOIN: keep log rows even if the member was deleted (member_id will be NULL)
LEFT JOIN public.members m ON m.id = rl.member_id;

COMMENT ON VIEW public.reminder_logs_view IS
  'Reminder logs with member name/phone via LEFT JOIN.
   LEFT JOIN ensures logs are visible even when member has been soft-deleted.';


-- ============================================================
-- SECTION 12: WORKOUTS
-- ============================================================
CREATE TABLE IF NOT EXISTS public.workouts (
  id          BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  member_id   BIGINT      NOT NULL REFERENCES public.members(id) ON DELETE CASCADE,
  trainer_id  BIGINT      REFERENCES public.trainers(id) ON DELETE SET NULL,
  title       TEXT        NOT NULL,
  -- Flexible JSON schedule: { mon: [...exercises], tue: [...], ... }
  schedule    JSONB       NOT NULL DEFAULT '{}',
  is_active   BOOLEAN     NOT NULL DEFAULT TRUE,
  -- Soft delete
  deleted_at  TIMESTAMPTZ,
  -- Audit
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by  UUID        REFERENCES public.profiles(id) ON DELETE SET NULL,
  updated_by  UUID        REFERENCES public.profiles(id) ON DELETE SET NULL
);

COMMENT ON TABLE public.workouts IS
  'Workout plans assigned to members. schedule is flexible JSONB.
   Soft-deleted so historical plans are retained.';

CREATE INDEX IF NOT EXISTS idx_workouts_member_id  ON public.workouts(member_id)  WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_workouts_trainer_id ON public.workouts(trainer_id) WHERE deleted_at IS NULL;

DROP TRIGGER IF EXISTS trg_workouts_updated_at ON public.workouts;
CREATE TRIGGER trg_workouts_updated_at
  BEFORE UPDATE ON public.workouts
  FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();


-- ============================================================
-- SECTION 13: DIET PLANS
-- ============================================================
CREATE TABLE IF NOT EXISTS public.diet_plans (
  id          BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  member_id   BIGINT      NOT NULL REFERENCES public.members(id) ON DELETE CASCADE,
  trainer_id  BIGINT      REFERENCES public.trainers(id) ON DELETE SET NULL,
  title       TEXT        NOT NULL,
  schedule    JSONB       NOT NULL DEFAULT '{}',
  is_active   BOOLEAN     NOT NULL DEFAULT TRUE,
  -- Soft delete
  deleted_at  TIMESTAMPTZ,
  -- Audit
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by  UUID        REFERENCES public.profiles(id) ON DELETE SET NULL,
  updated_by  UUID        REFERENCES public.profiles(id) ON DELETE SET NULL
);

COMMENT ON TABLE public.diet_plans IS
  'Diet/nutrition plans assigned to members. schedule is flexible JSONB.';

CREATE INDEX IF NOT EXISTS idx_diet_plans_member_id ON public.diet_plans(member_id) WHERE deleted_at IS NULL;

DROP TRIGGER IF EXISTS trg_diet_plans_updated_at ON public.diet_plans;
CREATE TRIGGER trg_diet_plans_updated_at
  BEFORE UPDATE ON public.diet_plans
  FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();


-- ============================================================
-- SECTION 14: EXPENSES
-- ============================================================
CREATE TABLE IF NOT EXISTS public.expenses (
  id            BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category      TEXT        NOT NULL
                  CHECK (category IN ('rent', 'equipment', 'utilities', 'salaries',
                                      'marketing', 'maintenance', 'supplements', 'other')),
  amount        NUMERIC(10, 2) NOT NULL CHECK (amount > 0),
  expense_date  DATE        NOT NULL DEFAULT CURRENT_DATE,
  description   TEXT,
  receipt_url   TEXT,
  -- Soft delete: expenses can be voided, not hard-deleted
  deleted_at    TIMESTAMPTZ,
  -- Audit
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by    UUID        REFERENCES public.profiles(id) ON DELETE SET NULL,
  updated_by    UUID        REFERENCES public.profiles(id) ON DELETE SET NULL
);

COMMENT ON TABLE public.expenses IS
  'Operating expense records. Soft-deleted via deleted_at for audit purposes.
   PRODUCTION: Add vendor_id FK if vendor management is needed.';

CREATE INDEX IF NOT EXISTS idx_expenses_date     ON public.expenses(expense_date) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_expenses_category ON public.expenses(category)    WHERE deleted_at IS NULL;

DROP TRIGGER IF EXISTS trg_expenses_updated_at ON public.expenses;
CREATE TRIGGER trg_expenses_updated_at
  BEFORE UPDATE ON public.expenses
  FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();


-- ============================================================
-- SECTION 15: LEADS  (Sales funnel / prospect management)
-- ============================================================
CREATE TABLE IF NOT EXISTS public.leads (
  id               BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name             TEXT        NOT NULL,
  phone            TEXT        NOT NULL,
  email            TEXT,
  source           TEXT        DEFAULT 'walk_in'
                     CHECK (source IN ('walk_in', 'instagram', 'referral',
                                       'google', 'facebook', 'other')),
  stage            TEXT        NOT NULL DEFAULT 'new'
                     CHECK (stage IN ('new', 'contacted', 'trial', 'converted', 'lost')),
  interested_plan  TEXT,
  assigned_to      UUID        REFERENCES public.profiles(id) ON DELETE SET NULL,
  follow_up_date   DATE,
  notes            TEXT,
  -- Set when stage transitions to 'converted'
  converted_at     TIMESTAMPTZ,
  -- Soft delete
  deleted_at       TIMESTAMPTZ,
  -- Audit
  created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by       UUID        REFERENCES public.profiles(id) ON DELETE SET NULL,
  updated_by       UUID        REFERENCES public.profiles(id) ON DELETE SET NULL
);

COMMENT ON TABLE public.leads IS
  'Sales pipeline for prospects/enquiries. Stage transitions are tracked.
   Soft-deleted leads remain for conversion rate analytics.';

CREATE INDEX IF NOT EXISTS idx_leads_stage       ON public.leads(stage)          WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_leads_follow_up   ON public.leads(follow_up_date) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_leads_assigned_to ON public.leads(assigned_to);

DROP TRIGGER IF EXISTS trg_leads_updated_at ON public.leads;
CREATE TRIGGER trg_leads_updated_at
  BEFORE UPDATE ON public.leads
  FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();


-- ============================================================
-- SECTION 16: VISITORS  (Walk-in / trial management)
-- ============================================================
CREATE TABLE IF NOT EXISTS public.visitors (
  id                   BIGINT    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name                 TEXT      NOT NULL,
  phone                TEXT      NOT NULL,
  purpose              TEXT      DEFAULT 'trial'
                         CHECK (purpose IN ('trial', 'enquiry', 'guest', 'event')),
  trial_date           DATE,
  interested_plan      TEXT,
  follow_up_date       DATE,
  assigned_to          UUID      REFERENCES public.profiles(id) ON DELETE SET NULL,
  -- Set when visitor converts to a paying member
  converted_member_id  BIGINT    REFERENCES public.members(id) ON DELETE SET NULL,
  -- Soft delete
  deleted_at           TIMESTAMPTZ,
  -- Audit
  created_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by           UUID        REFERENCES public.profiles(id) ON DELETE SET NULL,
  updated_by           UUID        REFERENCES public.profiles(id) ON DELETE SET NULL
);

COMMENT ON TABLE public.visitors IS
  'Walk-in visitors and trial members. converted_member_id links to
   the members table when the visitor joins as a paying member.';

CREATE INDEX IF NOT EXISTS idx_visitors_trial_date ON public.visitors(trial_date) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_visitors_assigned_to ON public.visitors(assigned_to);

DROP TRIGGER IF EXISTS trg_visitors_updated_at ON public.visitors;
CREATE TRIGGER trg_visitors_updated_at
  BEFORE UPDATE ON public.visitors
  FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();


-- ============================================================
-- SECTION 17: ROW LEVEL SECURITY (RLS)
-- ============================================================
-- DEVELOPMENT POLICY (current):
--   Authenticated users can SELECT and mutate all rows.
--   Unauthenticated (anon) users have ZERO access.
--
-- ⚠️  PRODUCTION UPGRADE CHECKLIST:
--   □ 1. Add `gym_id UUID` to every table for multi-tenant isolation.
--   □ 2. Set `gym_id = (SELECT gym_id FROM profiles WHERE id = auth.uid())`
--        in all RLS policies.
--   □ 3. Restrict DELETE/UPDATE to admin roles:
--          USING (EXISTS(SELECT 1 FROM profiles WHERE id = auth.uid()
--                        AND role IN ('super_admin','admin')))
--   □ 4. Move api_key / Twilio credentials to Supabase Vault.
--   □ 5. Implement a separate audit_log table triggered on sensitive mutations.
--   □ 6. Use Supabase Edge Functions for all messaging (never expose Twilio from client).
--   □ 7. Rate-limit anon requests via Supabase middleware.
--   □ 8. Enable email confirmation for new staff accounts.
-- ============================================================

DO $$
DECLARE
  tbl TEXT;
BEGIN
  FOR tbl IN SELECT UNNEST(ARRAY[
    'profiles', 'membership_plans', 'trainers', 'members',
    'payments', 'attendance', 'settings', 'notifications',
    'activities', 'whatsapp_config', 'reminder_logs',
    'workouts', 'diet_plans', 'expenses', 'leads', 'visitors'
  ]) LOOP
    -- Enable RLS
    EXECUTE FORMAT('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY;', tbl);

    -- Remove old open-access policies from v1 if they exist
    EXECUTE FORMAT(
      'DROP POLICY IF EXISTS "Enable all access for anon" ON public.%I;', tbl
    );

    -- DEVELOPMENT: authenticated users can read anything
    EXECUTE FORMAT(
      'DROP POLICY IF EXISTS "dev_select_authenticated" ON public.%I;
       CREATE POLICY "dev_select_authenticated" ON public.%I
         FOR SELECT TO authenticated USING (true);',
      tbl, tbl
    );

    -- DEVELOPMENT: authenticated users can mutate anything
    EXECUTE FORMAT(
      'DROP POLICY IF EXISTS "dev_all_authenticated" ON public.%I;
       CREATE POLICY "dev_all_authenticated" ON public.%I
         FOR ALL TO authenticated USING (true) WITH CHECK (true);',
      tbl, tbl
    );
  END LOOP;
END $$;


-- ============================================================
-- SECTION 18: REALTIME SUBSCRIPTIONS
-- Enable Postgres CDC for core tables the React app subscribes to.
-- ============================================================
DO $$
BEGIN
  -- Attempt to add tables; silently ignore if already subscribed
  BEGIN
    ALTER PUBLICATION supabase_realtime ADD TABLE
      public.members,
      public.payments,
      public.attendance,
      public.trainers,
      public.notifications,
      public.activities,
      public.settings,
      public.reminder_logs;
  EXCEPTION
    WHEN duplicate_object THEN NULL;
    WHEN OTHERS          THEN NULL;
  END;
END $$;


-- ============================================================
-- SECTION 19: VERIFICATION QUERY
-- Run this to confirm all 16 tables exist and have correct columns.
-- Expected output: 16 rows, each with a column_count > 0.
-- ============================================================
SELECT
  t.table_name,
  COUNT(c.column_name)                                   AS column_count,
  CASE t.table_type WHEN 'BASE TABLE' THEN 'TABLE' ELSE t.table_type END AS type
FROM information_schema.tables t
JOIN information_schema.columns c
  ON  c.table_schema = t.table_schema
  AND c.table_name   = t.table_name
WHERE t.table_schema = 'public'
  AND t.table_name IN (
    'profiles', 'membership_plans', 'trainers', 'members',
    'payments', 'attendance', 'settings', 'notifications',
    'activities', 'whatsapp_config', 'reminder_logs',
    'workouts', 'diet_plans', 'expenses', 'leads', 'visitors'
  )
GROUP BY t.table_name, t.table_type
ORDER BY t.table_name;
