-- ============================================================
-- TTZ FITNESS CLUB — Migration v3.0 (Enterprise Production Upgrade)
-- Run AFTER supabase_migration.sql (v2.0)
-- ============================================================
-- PURPOSE:
--   • Add enterprise fields to members, payments, attendance
--   • Add measurements table
--   • Add WhatsApp tables (sessions, templates, rules, queue, history)
--   • Add activity_logs (enterprise audit trail)
--   • Update members_view to include new fields
--   • Seed correct TTZ business settings
-- ============================================================

-- ============================================================
-- SECTION A: MEASUREMENTS TABLE
-- ============================================================
CREATE TABLE IF NOT EXISTS public.measurements (
  id          BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  member_id   BIGINT      NOT NULL REFERENCES public.members(id) ON DELETE CASCADE,
  date        DATE        NOT NULL DEFAULT CURRENT_DATE,
  weight      NUMERIC(5,2),
  body_fat    NUMERIC(5,2),
  chest       NUMERIC(5,2),
  waist       NUMERIC(5,2),
  hips        NUMERIC(5,2),
  arms        NUMERIC(5,2),
  thighs      NUMERIC(5,2),
  notes       TEXT,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by  UUID        REFERENCES public.profiles(id) ON DELETE SET NULL,
  CONSTRAINT uq_measurements_member_date UNIQUE (member_id, date)
);

COMMENT ON TABLE public.measurements IS
  'Body measurement history per member. One row per member per date.';

CREATE INDEX IF NOT EXISTS idx_measurements_member_id ON public.measurements(member_id);
CREATE INDEX IF NOT EXISTS idx_measurements_date      ON public.measurements(date);

ALTER TABLE public.measurements ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "auth_full_access_measurements" ON public.measurements;
CREATE POLICY "auth_full_access_measurements"
  ON public.measurements FOR ALL
  USING (auth.role() = 'authenticated')
  WITH CHECK (auth.role() = 'authenticated');

-- ============================================================
-- SECTION B: EXTENDED MEMBER FIELDS
-- ============================================================
ALTER TABLE public.members
  ADD COLUMN IF NOT EXISTS gender             TEXT    CHECK (gender IN ('male','female','other','prefer_not_to_say')),
  ADD COLUMN IF NOT EXISTS date_of_birth      DATE,
  ADD COLUMN IF NOT EXISTS address            TEXT,
  ADD COLUMN IF NOT EXISTS emergency_contact       TEXT,
  ADD COLUMN IF NOT EXISTS emergency_contact_name  TEXT,
  ADD COLUMN IF NOT EXISTS blood_group        TEXT    CHECK (blood_group IN ('A+','A-','B+','B-','O+','O-','AB+','AB-','Unknown')),
  ADD COLUMN IF NOT EXISTS medical_conditions TEXT,
  ADD COLUMN IF NOT EXISTS profile_photo      TEXT,
  ADD COLUMN IF NOT EXISTS membership_status  TEXT    NOT NULL DEFAULT 'active'
                              CHECK (membership_status IN ('active','frozen','cancelled')),
  ADD COLUMN IF NOT EXISTS renewal_count      INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS is_active          BOOLEAN NOT NULL DEFAULT TRUE;

-- ============================================================
-- SECTION C: EXTENDED PAYMENT FIELDS
-- ============================================================
ALTER TABLE public.payments
  ADD COLUMN IF NOT EXISTS invoice_number    TEXT,
  ADD COLUMN IF NOT EXISTS receipt_number    TEXT,
  ADD COLUMN IF NOT EXISTS transaction_id    TEXT,
  ADD COLUMN IF NOT EXISTS payment_reference TEXT,
  ADD COLUMN IF NOT EXISTS payment_gateway   TEXT,
  ADD COLUMN IF NOT EXISTS discount          NUMERIC(10,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS tax               NUMERIC(10,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS subtotal          NUMERIC(10,2),
  ADD COLUMN IF NOT EXISTS final_amount      NUMERIC(10,2),
  ADD COLUMN IF NOT EXISTS collected_by      UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS remarks           TEXT;

-- Backfill subtotal and final_amount for existing rows
UPDATE public.payments
  SET subtotal = amount, final_amount = amount
  WHERE subtotal IS NULL;

-- ============================================================
-- SECTION D: EXTENDED ATTENDANCE FIELDS
-- ============================================================
ALTER TABLE public.attendance
  ADD COLUMN IF NOT EXISTS check_out_time     TEXT,
  ADD COLUMN IF NOT EXISTS attendance_method  TEXT NOT NULL DEFAULT 'manual'
                              CHECK (attendance_method IN ('manual','qr','biometric','app')),
  ADD COLUMN IF NOT EXISTS marked_by          UUID REFERENCES public.profiles(id) ON DELETE SET NULL;

-- ============================================================
-- SECTION E: REBUILD members_view WITH NEW FIELDS
-- ============================================================
CREATE OR REPLACE VIEW public.members_view AS
SELECT
  m.id,
  m.name,
  m.phone,
  m.email,
  m.plan,
  m.plan_id,
  m.join_date,
  m.expiry_date,
  GREATEST(0, (m.expiry_date - CURRENT_DATE)::INTEGER)   AS days_remaining,
  CASE
    WHEN m.expiry_date < CURRENT_DATE               THEN 'expired'
    WHEN m.expiry_date <= (CURRENT_DATE + 5)        THEN 'expiring'
    ELSE                                                 'active'
  END                                                     AS status,
  m.trainer_id,
  m.weight,
  m.target_weight,
  m.height,
  m.body_fat,
  m.before_image,
  m.after_image,
  m.last_visit,
  m.notes,
  -- New enterprise fields
  m.gender,
  m.date_of_birth,
  m.address,
  m.emergency_contact,
  m.emergency_contact_name,
  m.blood_group,
  m.medical_conditions,
  m.profile_photo,
  m.membership_status,
  m.renewal_count,
  m.is_active,
  m.created_at,
  m.updated_at,
  m.created_by,
  m.updated_by
FROM public.members m
WHERE m.deleted_at IS NULL;

-- ============================================================
-- SECTION F: WHATSAPP ENTERPRISE TABLES
-- ============================================================

-- WhatsApp Sessions (QR code, connection state)
CREATE TABLE IF NOT EXISTS public.whatsapp_sessions (
  id            BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_name  TEXT        NOT NULL DEFAULT 'default',
  status        TEXT        NOT NULL DEFAULT 'disconnected'
                              CHECK (status IN ('connected','disconnected','connecting','error')),
  qr_code       TEXT,
  phone_number  TEXT,
  connected_at  TIMESTAMPTZ,
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

INSERT INTO public.whatsapp_sessions (session_name, status)
VALUES ('default', 'disconnected')
ON CONFLICT DO NOTHING;

-- WhatsApp Templates
CREATE TABLE IF NOT EXISTS public.whatsapp_templates (
  id          BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        TEXT        NOT NULL,
  category    TEXT        NOT NULL DEFAULT 'custom'
                CHECK (category IN ('expiry','payment','attendance','welcome','promo','birthday','custom')),
  message     TEXT        NOT NULL,
  variables   TEXT[]      NOT NULL DEFAULT '{}',
  is_active   BOOLEAN     NOT NULL DEFAULT TRUE,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by  UUID        REFERENCES public.profiles(id) ON DELETE SET NULL
);

-- Seed default templates
INSERT INTO public.whatsapp_templates (name, category, message, variables) VALUES
  ('Membership Expiry',  'expiry',     'Hi {name}! 👋 Your TTZ membership expires on {expiry_date}. Renew now to keep your fitness journey going! 💪 Call us: 8668891406', ARRAY['{name}','{expiry_date}']),
  ('Payment Reminder',   'payment',    'Hi {name}! A payment of ₹{amount} is due for your {plan} plan at TTZ. Please clear it at your earliest. 🙏', ARRAY['{name}','{amount}','{plan}']),
  ('Welcome Message',    'welcome',    'Welcome to The Transformation Zone (TTZ), {name}! 🎉 We''re thrilled to have you. Your fitness journey starts NOW! 💪 Fitness | Focus | Future', ARRAY['{name}']),
  ('Birthday Greetings', 'birthday',   'Happy Birthday {name}! 🎂 The entire TTZ family wishes you a fantastic day. Here''s to a healthier, stronger you! 💪', ARRAY['{name}']),
  ('Low Attendance',     'attendance', 'Hey {name}, we miss you at TTZ! 😢 You haven''t visited in a while. Your fitness goals are waiting for you! Come back strong! 💪', ARRAY['{name}'])
ON CONFLICT DO NOTHING;

-- Automation Rules
CREATE TABLE IF NOT EXISTS public.automation_rules (
  id              BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name            TEXT        NOT NULL,
  trigger_event   TEXT        NOT NULL
                    CHECK (trigger_event IN ('expiry_7d','expiry_3d','expiry_1d','payment_due','no_attendance_7d','no_attendance_14d','birthday','new_member')),
  template_id     BIGINT      REFERENCES public.whatsapp_templates(id) ON DELETE SET NULL,
  is_active       BOOLEAN     NOT NULL DEFAULT TRUE,
  last_run_at     TIMESTAMPTZ,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by      UUID        REFERENCES public.profiles(id) ON DELETE SET NULL
);

-- Seed default automation rules
INSERT INTO public.automation_rules (name, trigger_event, template_id, is_active)
SELECT 'Expiry 7-Day Alert', 'expiry_7d', id, TRUE
  FROM public.whatsapp_templates WHERE name = 'Membership Expiry' LIMIT 1
ON CONFLICT DO NOTHING;

-- Message Queue
CREATE TABLE IF NOT EXISTS public.message_queue (
  id            BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  member_id     BIGINT      REFERENCES public.members(id) ON DELETE CASCADE,
  phone         TEXT        NOT NULL,
  message       TEXT        NOT NULL,
  template_id   BIGINT      REFERENCES public.whatsapp_templates(id) ON DELETE SET NULL,
  rule_id       BIGINT      REFERENCES public.automation_rules(id) ON DELETE SET NULL,
  status        TEXT        NOT NULL DEFAULT 'pending'
                  CHECK (status IN ('pending','processing','sent','failed','cancelled')),
  scheduled_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  processed_at  TIMESTAMPTZ,
  error_message TEXT,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_message_queue_status      ON public.message_queue(status);
CREATE INDEX IF NOT EXISTS idx_message_queue_scheduled   ON public.message_queue(scheduled_at);

-- Delivery History
CREATE TABLE IF NOT EXISTS public.delivery_history (
  id            BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  queue_id      BIGINT      REFERENCES public.message_queue(id) ON DELETE SET NULL,
  member_id     BIGINT      REFERENCES public.members(id) ON DELETE SET NULL,
  phone         TEXT        NOT NULL,
  message       TEXT        NOT NULL,
  status        TEXT        NOT NULL DEFAULT 'delivered'
                  CHECK (status IN ('delivered','failed','bounced','read')),
  provider      TEXT,
  provider_id   TEXT,
  sent_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  read_at       TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_delivery_history_member   ON public.delivery_history(member_id);
CREATE INDEX IF NOT EXISTS idx_delivery_history_sent_at  ON public.delivery_history(sent_at DESC);

-- ============================================================
-- SECTION G: ACTIVITY LOGS (Enterprise Audit Trail)
-- Replaces the basic `activities` table with full audit detail
-- ============================================================
CREATE TABLE IF NOT EXISTS public.activity_logs (
  id              BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id         UUID        REFERENCES public.profiles(id) ON DELETE SET NULL,
  user_name       TEXT,
  module          TEXT        NOT NULL,
  action          TEXT        NOT NULL,
  entity_type     TEXT,
  entity_id       TEXT,
  prev_value      JSONB,
  new_value       JSONB,
  ip_address      TEXT,
  device          TEXT,
  notes           TEXT,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE public.activity_logs IS
  'Enterprise-grade audit trail. Every significant action is logged here.
   prev_value and new_value store the before/after state as JSONB.
   Append-only — never update or delete rows.';

CREATE INDEX IF NOT EXISTS idx_activity_logs_user_id    ON public.activity_logs(user_id);
CREATE INDEX IF NOT EXISTS idx_activity_logs_module     ON public.activity_logs(module);
CREATE INDEX IF NOT EXISTS idx_activity_logs_created_at ON public.activity_logs(created_at DESC);

-- ============================================================
-- SECTION H: RLS FOR NEW TABLES
-- ============================================================
DO $$
DECLARE tbl TEXT;
BEGIN
  FOR tbl IN SELECT UNNEST(ARRAY[
    'measurements','whatsapp_sessions','whatsapp_templates',
    'automation_rules','message_queue','delivery_history','activity_logs'
  ]) LOOP
    EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', tbl);
    EXECUTE format('DROP POLICY IF EXISTS "auth_full_access_%1$s" ON public.%1$I', tbl);
    EXECUTE format(
      'CREATE POLICY "auth_full_access_%1$s" ON public.%1$I FOR ALL
       USING (auth.role() = ''authenticated'')
       WITH CHECK (auth.role() = ''authenticated'')',
      tbl
    );
  END LOOP;
END $$;

-- ============================================================
-- SECTION I: UPDATE SETTINGS WITH TTZ PRODUCTION VALUES
-- ============================================================
INSERT INTO public.settings (key, value, description) VALUES
  ('gym_name',        'The Transformation Zone (TTZ)',                     'Display name of the gym'),
  ('tagline',         'Fitness | Focus | Future',                          'Branding tagline'),
  ('gym_type',        'Premium Unisex Gym & Nutrition Club',               'Gym type descriptor'),
  ('primary_phone',   '8668891406',                                        'Primary contact number'),
  ('secondary_phone', '9028468563',                                        'Secondary contact number'),
  ('email',           'ttz@gmail.com',                                     'Primary contact email'),
  ('instagram',       '@ttz_fitness_24',                                   'Instagram handle'),
  ('address',         'Near Ayyappa Swami Temple, Plot No. 11, Gut No. 142, Hanuman Temple, Satara, Chhatrapati Sambhajinagar, Maharashtra', 'Gym physical address'),
  ('opening_time',    '05:00',                                             'Daily opening time (HH:MM)'),
  ('closing_time',    '23:00',                                             'Daily closing time (HH:MM)'),
  ('expiry_alerts',   'true',                                              'Enable membership expiry alerts'),
  ('payment_reminders','true',                                             'Enable pending payment reminders'),
  ('new_member_alerts','true',                                             'Enable new member notifications'),
  ('brand_color',     'amber',                                             'UI brand color'),
  ('software_version','3.0.0',                                             'TTZ Software version'),
  ('software_name',   'TTZ Gym Management Software',                       'Software product name'),
  ('engineer',        'Rexora',                                            'Engineering company'),
  ('developer',       'Aditya Kittad',                                     'Founder & Lead Developer')
ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value;

-- ============================================================
-- SECTION J: VERIFY ALL TABLES EXIST
-- ============================================================
SELECT table_name, table_type
FROM information_schema.tables
WHERE table_schema = 'public'
  AND table_name IN (
    'profiles','membership_plans','trainers','members',
    'payments','attendance','settings','notifications',
    'activities','whatsapp_config','reminder_logs',
    'workouts','diet_plans','expenses','leads','visitors',
    'measurements','whatsapp_sessions','whatsapp_templates',
    'automation_rules','message_queue','delivery_history','activity_logs'
  )
ORDER BY table_name;
