const { Client } = require('pg');
const client = new Client({
  connectionString: 'postgresql://postgres:8796700769ttz@db.opgvkocbpnvutoagyfhc.supabase.co:5432/postgres',
  ssl: { rejectUnauthorized: false }
});

async function fixActivities() {
  await client.connect();
  console.log('Connected');
  try {
    await client.query('DROP TABLE IF EXISTS public.activities CASCADE;');
    await client.query(`
      CREATE TABLE public.activities (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        type VARCHAR(100),
        member_id UUID REFERENCES public.members(id) ON DELETE CASCADE,
        name VARCHAR(255),
        action TEXT,
        time VARCHAR(50),
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      );
    `);
    console.log('Recreated activities table to match frontend');
  } catch (err) {
    console.error(err);
  } finally {
    await client.end();
  }
}
fixActivities();
