import * as XLSX from 'xlsx';
import jsPDF from 'jspdf';
import 'jspdf-autotable';
import { format } from 'date-fns';

interface ExportMetadata {
  title: string;
  period: string;
  generatedBy: string;
  totalRecords: number;
  totalPresent: number;
  totalAbsent: number;
  gymName?: string;
  gymAddress?: string;
  gymPhone?: string;
}

export const exportToExcel = (data: any[], filename: string, meta: ExportMetadata) => {
  const wb = XLSX.utils.book_new();
  
  // Create header meta
  const wsData = [
    [meta.gymName || 'The Transformation Zone (TTZ)'],
    [meta.title],
    [`Report Period: ${meta.period}`],
    [`Generated By: ${meta.generatedBy}`],
    [`Generated At: ${format(new Date(), 'dd MMM yyyy, hh:mm a')}`],
    [],
    [`Total Records: ${meta.totalRecords}`, `Present: ${meta.totalPresent}`, `Absent: ${meta.totalAbsent}`],
    [],
    // Table Headers
    ['Date', 'Check-in', 'Check-out', 'Member ID', 'Name', 'Phone', 'Plan', 'Coach', 'Status', 'Method', 'Remarks', 'Marked By']
  ];

  // Map Data
  data.forEach(row => {
    wsData.push([
      row.date ? format(new Date(row.date), 'dd MMM yyyy') : '-',
      row.checkInTime ? format(new Date(row.checkInTime), 'hh:mm a') : '-',
      row.checkOutTime ? format(new Date(row.checkOutTime), 'hh:mm a') : '-',
      row.memberId ? `#${String(row.memberId).slice(0, 8)}` : '-',
      row.memberName || '-',
      row.memberPhone || '-',
      row.plan || '-',
      row.coach || '-',
      (row.status || '').toUpperCase(),
      row.method || 'Manual',
      row.remarks || '-',
      row.markedBy || 'System'
    ]);
  });

  const ws = XLSX.utils.aoa_to_sheet(wsData);

  // Auto-size columns roughly
  const colWidths = [15, 12, 12, 12, 25, 15, 15, 20, 10, 10, 20, 15];
  ws['!cols'] = colWidths.map(w => ({ wch: w }));

  // Style header (XLSX free version doesn't support complex styles out of the box, but structure is good)
  XLSX.utils.book_append_sheet(wb, ws, 'Attendance');
  XLSX.writeFile(wb, `${filename}.xlsx`);
};

export const exportToCSV = (data: any[], filename: string) => {
  const headers = ['Date', 'Check-in', 'Check-out', 'Member ID', 'Name', 'Phone', 'Plan', 'Coach', 'Status', 'Method', 'Remarks', 'Marked By'];
  
  const csvRows = [
    headers.join(','),
    ...data.map(row => {
      return [
        row.date ? format(new Date(row.date), 'dd MMM yyyy') : '-',
        row.checkInTime ? format(new Date(row.checkInTime), 'hh:mm a') : '-',
        row.checkOutTime ? format(new Date(row.checkOutTime), 'hh:mm a') : '-',
        row.memberId ? `#${String(row.memberId).slice(0, 8)}` : '-',
        `"${row.memberName || '-'}"`,
        row.memberPhone || '-',
        `"${row.plan || '-'}"`,
        `"${row.coach || '-'}"`,
        (row.status || '').toUpperCase(),
        row.method || 'Manual',
        `"${row.remarks || '-'}"`,
        `"${row.markedBy || 'System'}"`
      ].join(',');
    })
  ];

  const blob = new Blob([csvRows.join('\n')], { type: 'text/csv;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.setAttribute('href', url);
  link.setAttribute('download', `${filename}.csv`);
  link.style.visibility = 'hidden';
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
};

export const exportToPDF = (data: any[], filename: string, meta: ExportMetadata) => {
  const doc = new jsPDF('landscape');
  
  // Headers
  doc.setFontSize(22);
  doc.setTextColor(40, 40, 40);
  doc.text(meta.gymName || 'The Transformation Zone (TTZ)', 14, 20);
  
  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  doc.text('Fitness • Focus • Future', 14, 26);
  if (meta.gymAddress) doc.text(meta.gymAddress, 14, 32);
  if (meta.gymPhone) doc.text(`Phone: ${meta.gymPhone}`, 14, 38);

  // Title
  doc.setFontSize(16);
  doc.setTextColor(0, 0, 0);
  doc.text(meta.title, 14, 50);

  doc.setFontSize(10);
  doc.text(`Report Period: ${meta.period}`, 14, 58);
  doc.text(`Generated By: ${meta.generatedBy} on ${format(new Date(), 'dd MMM yyyy, hh:mm a')}`, 14, 64);
  
  doc.text(`Total Records: ${meta.totalRecords} | Present: ${meta.totalPresent} | Absent: ${meta.totalAbsent}`, 14, 70);

  const tableCol = ['Date', 'Check-in', 'Check-out', 'Name', 'Phone', 'Plan', 'Coach', 'Status'];
  const tableRows = data.map(row => [
    row.date ? format(new Date(row.date), 'dd MMM yyyy') : '-',
    row.checkInTime ? format(new Date(row.checkInTime), 'hh:mm a') : '-',
    row.checkOutTime ? format(new Date(row.checkOutTime), 'hh:mm a') : '-',
    row.memberName || '-',
    row.memberPhone || '-',
    row.plan || '-',
    row.coach || '-',
    (row.status || '').toUpperCase()
  ]);

  (doc as any).autoTable({
    startY: 75,
    head: [tableCol],
    body: tableRows,
    theme: 'grid',
    headStyles: { fillColor: [40, 40, 40], textColor: [255, 255, 255] },
    alternateRowStyles: { fillColor: [245, 245, 245] },
    margin: { top: 75 },
    didDrawPage: (data: any) => {
      // Footer
      const str = `Page ${doc.internal.pages.length - 1}`;
      doc.setFontSize(8);
      doc.setTextColor(150, 150, 150);
      doc.text(str, data.settings.margin.left, doc.internal.pageSize.height - 10);
      
      const footerTxt = 'Generated using TTZ Gym Management Software | Engineered by Rexora | Aditya Kittad';
      doc.text(footerTxt, doc.internal.pageSize.width - data.settings.margin.right - doc.getTextWidth(footerTxt), doc.internal.pageSize.height - 10);
    }
  });

  doc.save(`${filename}.pdf`);
};

export const printAttendanceRegister = () => {
  window.print();
};
